---
# Destroy ELB  
- name: Destroy load balancer
  elb_application_lb:
    region: ap-southeast-2
    name: "{{ env_name }}-elb-{{ VPC_ID }}"
    state: absent
    wait: True

- pause:
    seconds: 15

# # Deregister the target from the target group
# - elb_target:
#     target_group_name: "{{ env_name }}_nxl_{{ VPC_ID }}"
#     target_id: "{{ INSTANCE_ID }}"
#     state: absent
#     Wait: True

# Create a target group with targets
- name: Destroy target group
  elb_target_group:
    region: ap-southeast-2
    name: "{{ env_name }}-tg-{{ VPC_ID }}"
    state: absent
    wait: True

# Get the details about the route53 entry for this instance
- name: Get the details of the route53 dns entry
  route53:
      state: get
      zone: oztaxa.com
      record: "{{ env_name }}.oztaxa.com"
      type: A
  register: dns_entry

# Print variable dns_entry
# - name: Print variable dns_entry
#   command: echo "DNS Entry:\ {{ dns_entry }}"

# Delete the alias route53 record for the instance
- name: Delete the route53 dns entry
  route53:
    state: absent
    zone: oztaxa.com
    record: "{{ env_name }}.oztaxa.com"
    type: A
    value: "{{ dns_entry['set']['value'] }}"
    alias: True
    alias_hosted_zone_id: "{{ dns_entry['set']['alias_hosted_zone_id'] }}"

- name: Destroy the ROSCO instance
  ec2:
   id: "{{ env_name }}_nxl_{{ VPC_ID }}"
   instance_ids: "{{ INSTANCE_ID }}"
   region: ap-southeast-2
   state: absent
   wait: True

# NOT USED ANYMORE
# - name: destroy ASG
#   ec2_asg:
#     name: "{{ nxl_env_name }}_asg_{{ VPC_ID }}"
#     state: absent
#     region: ap-southeast-2
#     wait_for_instances: false

# - name: destroy launch config
#   ec2_lc:
#     name: "{{ nxl_env_name }}_lc_{{ VPC_ID }}"
#     state: absent
#     region: ap-southeast-2

# - name: Destroy sg for taxaas ELB and EC2Instance
#   ec2_group:
#     name: "{{item.sgname}}"
#     description: sg for taxaas ELB
#     region: ap-southeast-2
#     state: absent
#   with_items:
#       - { sgname: "NXL-lb-sg-{{ VPC_ID }}" }
#       - { sgname: "NXL-app-sg-{{ VPC_ID }}" }

